// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhBkTUX-q9SNBIXVW8j5UcQ-i8NMYtin4',
    appId: '1:517847736235:web:048f64e64954d38904fcee',
    messagingSenderId: '517847736235',
    projectId: 'flutter-crud1122',
    authDomain: 'flutter-crud1122.firebaseapp.com',
    storageBucket: 'flutter-crud1122.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5jWFWnch1cA9hZ0ZyxOoKN9uoMnP5k5w',
    appId: '1:517847736235:android:d13471e6511d2cee04fcee',
    messagingSenderId: '517847736235',
    projectId: 'flutter-crud1122',
    storageBucket: 'flutter-crud1122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFaXOfvr36DF8Xauv1Zi43JTwaOsqgQ_U',
    appId: '1:517847736235:ios:ed29a37eed3af2b204fcee',
    messagingSenderId: '517847736235',
    projectId: 'flutter-crud1122',
    storageBucket: 'flutter-crud1122.appspot.com',
    iosClientId: '517847736235-vtv6pl9rip98al7hknh7mkr9khqp5grl.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFaXOfvr36DF8Xauv1Zi43JTwaOsqgQ_U',
    appId: '1:517847736235:ios:ed29a37eed3af2b204fcee',
    messagingSenderId: '517847736235',
    projectId: 'flutter-crud1122',
    storageBucket: 'flutter-crud1122.appspot.com',
    iosClientId: '517847736235-vtv6pl9rip98al7hknh7mkr9khqp5grl.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
